### ISSUE TITLE
Failed to instantiate module cordovaHTTP due to

### ISSUE THREAD

**Issue by franciswagner** [wymsee/cordova-HTTP#55]
I'm trying to use this module on my Cordova/Ionic project and I've loaded the module according to the documentation, but when I try to use cordovaHTTP.enableSSLPinning it gives me the following error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module cordovaHTTP due to:
Error: [$injector:nomod] Module 'cordovaHTTP' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.6/$injector/nomod?p0=cordovaHTTP
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:7888:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:9576:17
    at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9500:38)
    at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9574:14)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11906:22
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11907:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=cordovaHTTP&p1=Erro…%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A11890%3A5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:7888:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11929:15
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11907:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:8147:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11890:5)
    at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11816:11)
    at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9263:20)
    at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9284:12)

**Comment by xael-fry** [comment]
+1

**Comment by shawns582** [comment]
Were you able to fix this?

**Comment by relicmelex** [comment]
+1.... anyone get this figured?

**Comment by relicmelex** [comment]
https://libraries.io/bower/ng-cordova-http give this a look, someone created an angular wrapper

**Comment by mxmzb** [comment]
having the same issue

**Comment by spoiledtechie** [comment]
same issue.

**Comment by Harshad111** [comment]
**Ionic Solution - but maybe helpful for others as well**
The ngCordovaHTTP module is very similar to the  what the plugin also includes - an angular module called cordovaHTTP, which also doesn't load in time to be injected into our app. Because I think its a load sequence issue. Some here have had luck ordering their scripts like so angular.js, cordovajs, app.js respectively, but not me.  

Some here have suggested to inject it manually later rather than adding it as a dependency and then you get the `[$injector:modulerr]` error. Anyways all logically workarounds failed.

**What worked**
Try... not calling any modules as dependencies and depend on cordova plugins to be loaded in the device ready function and then use it. This works even for Ionic (using $ionicPlatform.ready) or

```
 document.addEventListener("deviceready", function () {
       console.log(window.CordovaHttpPlugin); //<--- this works
});
```
So instead of CordovaHTTP.get, you would use  window.CordovaHttpPlugin.get and so on.

**Why CordovaHttpPlugin?**
Notice that the plugin is exported as `cordova.define("cordova-plugin-http.**CordovaHttpPlugin**", function(require, exports, module) {` 
- first line in cordovaHTTP.js - once your project is updated..using **cordova platform update android**

**File Location:** <project location>\platform\assets\www\plugins\cordova-plugin-http\www\cordovaHTTP.js

and so you should use ` window.CorodovaHttpPlugin ` inside the device ready event.

**Other forks**
There are a couple of forks for this, that you may want to keep an eye on which is more recent and has additional functionality and use them instead.

https://github.com/Telerik-Verified-Plugins/SecureHTTP 
https://github.com/serviewcare/cordova-HTTP

The documentation however is not helpful as it points back to this one - you could add them instead using the git name. 

eg. `cordova plugin add https://github.com/serviewcare/cordova-HTTP.git `
