### ISSUE TITLE
cannot install with cordova

### ISSUE THREAD

**Issue by Mirodil** [wymsee/cordova-HTTP#66]
cannot install with the following command
```
cordova plugin add https://github.com/wymsee/cordova-HTTP.git
```
got the following error
```
e:\Javascript\MapAm>cordova plugin add https://github.com/wymsee/cordova-HTTP.gi
t
Fetching plugin "https://github.com/wymsee/cordova-HTTP.git" via git clone
Repository "https://github.com/wymsee/cordova-HTTP.git" checked out to git ref "
master".
Installing "com.synconset.cordovaHTTP" for android
Notice: org.apache.cordova.file has been automatically converted to cordova-plug
in-file and fetched from npm. This is due to our old plugins registry shutting d
own.
Fetching plugin "https://github.com/apache/cordova-plugin-file" via git clone
Repository "https://github.com/apache/cordova-plugin-file" checked out to git re
f "r0.2.5".
Failed to install 'com.synconset.cordovaHTTP':Error: Expected plugin to have ID
"cordova-plugin-file" but got "org.apache.cordova.file".
    at checkID (C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\node_m
odules\cordova-lib\src\plugman\fetch.js:181:15)
    at C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-lib\src\plugman\fetch.js:166:9
    at _fulfilled (C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\nod
e_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Mirodil\AppData\Roaming\npm\node_modu
les\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Mirodil\AppData\Roaming\npm\nod
e_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\node_modu
les\q\q.js:796:13)
    at C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\node_modules\co
rdova-lib\node_modules\cordova-common\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\node
_modules\cordova-lib\node_modules\cordova-common\node_modules\q\q.js:137:13)
    at flush (C:\Users\Mirodil\AppData\Roaming\npm\node_modules\cordova\node_mod
ules\cordova-lib\node_modules\cordova-common\node_modules\q\q.js:125:13)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Error: Expected plugin to have ID "cordova-plugin-file" but got "org.apache.cord
ova.file".

```

**Comment by DazChong** [comment]
I spent more time debugging Cordova instead of development. Even the plugin ID outdated and no one care..

**Comment by T1st3** [comment]
@Mirodil 
I susually manage to install the plugin if I follow these steps (in order):
1 - Add platform (android, ios): `cordova platform add android`
2 - Add cordova-plugin-file: `cordova plugin add cordova-plugin-file`
3 - finally, add cordova-HTTP: `cordova plugin add https://github.com/wymsee/cordova-HTTP.git`

Hope it will do the trick for you.


Then, @DazChong, many Cordova plugins are made by individuals on their free time. There's no warranty that plugins or Cordova itself won't have bugs when you install them. You should commit your debugging back to the community, rather than complaining without participating. Your comment is not constructive.

**Comment by Mirodil** [comment]
ok
